name: cost-accounting

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:8070"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - cost-accounting-network
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://api:8070/healthcheck" ]
      interval: 30s
      timeout: 10s
      retries: 3
    init: true

networks:
  cost-accounting-network:
    driver: bridge